version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "bazel"
      include: "scope"
