name: CI

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci-format:
    runs-on: ubuntu-24.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Buildifier
        run: |
          wget "https://github.com/bazelbuild/buildtools/releases/download/v${BUILDIFIER_VERSION}/buildifier-linux-amd64" -O buildifier
          chmod +x ./buildifier
          ./buildifier -lint=warn -mode=check -warnings=all -r ${{ github.workspace }}
          rm ./buildifier
        env:
          BUILDIFIER_VERSION: 8.2.0

      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: -e -d

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: '.'
          extensions: 'h,c,cc,proto'
          clangFormatVersion: 14
