name: Test Python

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/test-bazel-target
        with:
          target: //test/python:test_runfiles

